import "styles/globals.css";
import { Inter } from "next/font/google";
import Navbar from "./(shared)/Navbar";
import MovieGenre from "./(shared)/MovieGenre";
import Input from "./(shared)/Input";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Imdb Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="sm:mx-0 mx-5">
            <nav>
              <Navbar />
            </nav>
            <section>
              <MovieGenre />
              <Input />
            </section>
            <main> {children}</main>
          </main>
        </Providers>
      </body>
    </html>
  );
}
